ci: add all default-enabled golangci-lint linters
This adds the enabled by default ones not in the current list.

Note that `govet` is a synonym for `vet`, use `govet` since it is the one used
in the list.

This brings up several issues:
    internal/commands/cnab_test.go:19:22: Error return value of `dockerCli.Initialize` is not checked (errcheck)
    	dockerCli.Initialize(cliflags.NewClientOptions())
    	                    ^
    internal/commands/completion.go:183:27: Error return value of `rootCmd.GenBashCompletion` is not checked (errcheck)
    	rootCmd.GenBashCompletion(buf)
    	                         ^
    internal/commands/push.go:186:13: Error return value of `r.out.Write` is not checked (errcheck)
    	r.out.Write(out.Bytes())
    	           ^
    internal/commands/root.go:52:17: Error return value of `dockerCli.Apply` is not checked (errcheck)
    	dockerCli.Apply(command.WithCombinedStreams(ioutil.Discard))
    	               ^
    internal/commands/root.go:54:18: Error return value of `dockerCli.Apply` is not checked (errcheck)
    		dockerCli.Apply(command.WithOutputStream(stdout), command.WithErrorStream(stderr))
    		               ^
    cmd/cnab-run/render.go:42:13: SA1006: printf-style function with dynamic first argument and no further arguments should use print-style function instead (staticcheck)
    	fmt.Printf(res)
    	           ^
    e2e/commands_test.go:74:3: SA4006: this value of `result` is never used (staticcheck)
    		result = icmd.RunCmd(cmd).Assert(t, icmd.Success)
    		^

Fix them all.

Signed-off-by: Ian Campbell <ijc@docker.com>